### ISSUE TITLE
What shall we do with a TODO?

### ISSUE THREAD

**Issue by dkfellows** [SpiNNakerManchester/SpiNNMachine#107]
https://github.com/SpiNNakerManchester/SpiNNMachine/blob/6cdc27b0023a7c55d3d34dcc1b6f0f8761edeec4/spinn_machine/virtual_machine.py#L279

Fix what it is talking about, or delete it. I don't know which, nor do I care very much. I just don't want a `TODO` flag hanging around in my IDE. 😄

**Comment by Christian-B** [comment]
Fixed in https://github.com/SpiNNakerManchester/SpiNNMachine/tree/wrapped2
