### ISSUE TITLE
1 way directional links error is an effort to interpret.

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNMachine#132]
Having responded to a issue on spynnaker8 about a report of uni directional links, and then getting my maths wrong on what link between which chips its actually pointing at. I think this error message could be reworked to report Exactly what link between which chips, in which direction is unidirectional. Which would be more helpful for debugging and would allow less maths to be required in interpreting said error message.

**Comment by Christian-B** [comment]
fixed in https://github.com/SpiNNakerManchester/SpiNNMachine/pull/133
