### ISSUE TITLE
Wraparounds on two board machines

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNMachine#134]
Found looking at https://github.com/SpiNNakerManchester/sPyNNaker8/issues/412

Depends on a reply from https://github.com/gblomqvist on how his boards are configured.

The current check is if a dimension is a multiple of 12 assume wraparrounds in the corresponding direction.

This test breaks for a 12 * 16 dimensions which two boards have.

Options.
1. Hard code the known wrap around sizes
2. Exclude 12 * 16 and 16 * 12 but keep al other multiples of 24
3. Hardcode 12 * 12 and change the test to multiples of 24
4. Hardcode 12 * 12 and other then except multiple of 12 greater than 12

**Comment by Christian-B** [comment]
Hardcode 12 * 12 and change the test to multiples of 24 will not work if the big machine has dimensions of 240 * 320  (30 * 40 boards)

My suggestion is to do 4. Hardcode 2 * 2, 12 * 12 and other then except multiple of 12 greater than 12

**Comment by Christian-B** [comment]
Correction all big machines are probably conmbination of racks.

Each rack is 48 * 24.  

So the test for multiples of 48 is valid,

**Comment by rowleya** [comment]
The big machine has dimensions of 240 x 240.  I would currently suggest that all 2-board systems must have wrap-arounds, meaning that they would end up being 12 x 12 but with holes.

**Comment by Christian-B** [comment]
If two boards report their size as 12 by 12 they are wrap arounds (with lots of missing chips) and nothing changes attached PR or not.

If the boards report their size as 12 * 16 the considering them half wraps is slightly wrong but the worse damage is that some routes between chips on opposite sides of a board may be less than optimal.

**Comment by Christian-B** [comment]
1. Turns out the user we thought had a two board machine actually has 2 machines both of normal sizes.

2. Any solution makes assumption about a future machine stepup we can not predict.

3. Considering a machine haveing wraps when it does not is unfortunate while considering a machine with wraps as not having them is breaking!  Why. False positive for wraps could result is some porr routing decisions while False negative for wrapping results in incorect mapping of chips to their eithernet chip.

Closed as not relevant any more.
