### ISSUE TITLE
SpiNNakerTriadGeometry get_potential_ethernet_chips incorrect

### ISSUE THREAD

**Issue by Christian-B** [SpiNNakerManchester/SpiNNMachine#78]
SpiNNakerTriadGeometry get_potential_ethernet_chips incorrect does not return all the ethernet chips if the size is not a multiple of a triad.

For example on a 20 by 20 board (6 boards so possible configuration) 0,12   12,12 and 12,0 are all missing despite being there.

ref: https://drive.google.com/open?id=0B9312BuJXntlQ1JMckZaZXYxMmM

This is caused by the method rounding down to the nearest triad size.
 Quick fix of not rounding down will add extra ones like  (8,16) but better too many than too few.

**Comment by rowleya** [comment]
I could be wrong, but I don't think you can have something that isn't a triad.  The rules are:
    - with_wraparounds = True, size is (2, 2) or each of x and y must be divisible by 12.
    - with_wraparounds = False, size = (2, 2), (8, 8) or x - 4, y - 4 must be divisible by 12.

I can see what you mean from the diagram of 20, 20 being possible though, so maybe this is the rule that is invalid?  Have you seen a 20, 20 board actually occur i.e. from spalloc?

Note that although the method is called "potential" ethernet chips, this is more referring to the fact that they are the chips that you can definitely connect to with Ethernet cables, but that those cables might be disconnected.  There is quite a bit of logic that I believe depends on this only ever giving actual board-relative 0, 0 chips.

**Comment by Christian-B** [comment]
No I can not say I ever saw a 20 20 machine.  I am just keeping an extremly open mind while converting the stuff to Java.

But I am uncomfortable will methods that rely on assumptions, where we do not have to.

"Ethernet" is being over used.
1. The chip connected to the cable.
2. The monitor chip.
3. The bottom left chip.

Of these only 3. Must be the local (0,0) but in this case it could be down.

In this class "ethernet" really only means bottom left/ local (0,0)

**Comment by rowleya** [comment]
We recently updated other parts of the code so that only single boards or multiples of triads are allowed.  We could update this code to error if the input is disallowed.

The only chips ever connected to Ethernet in a SpiNN-5 board are the local 0,0 bottom-right chips.  This is why we tend to call them the Ethernet chips.  The software currently requires all of these to be connected to function, in particular when using data out.  This could probably be fixed with a bit of effort.

**Comment by Christian-B** [comment]
I would NOT recommend trying to get the code to work with boards missing the 0,0 chip.  That assumption is hard coded in toooooooooo many places.

This method is not the place to be checking for multiples of triads.   Either the miachine size has already been refused (as is currrently the case) or this method should try its best.

As for spalloc. It desribes the machine so models to build the machine like this one should never be used.

So I agree that as the code is it will always produce the correct result when asked with the current machine sizes but wanted the Java to be as flexible as possible without complicating things. So pushed my solution there to here.

**Comment by Christian-B** [comment]
Similar too https://github.com/SpiNNakerManchester/SpiNNMachine/issues/91

**Comment by rowleya** [comment]
The PR of this has been merged.  Should this be closed?

**Comment by Christian-B** [comment]
Fixed
