### ISSUE TITLE
Get rid of the max core ID constructor parameter in python 

### ISSUE THREAD

**Issue by alan-stokes** [SpiNNakerManchester/SpiNNMachine#92]
see https://github.com/SpiNNakerManchester/JavaSpiNNaker/pull/219

will take on when have time

**Comment by andrewgait** [comment]
This is really a SpiNNMan issue I think (in fact, there already is an issue about it at https://github.com/SpiNNakerManchester/SpiNNMan/issues/146).  I don’t think there’s anything here in SpiNNMachine that uses it... ?

**Comment by alan-stokes** [comment]
fair enough. will kill
